apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: ${namespace}
  labels:
    app: coordinator
spec:
  replicas: ${coordinator_replicas}
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: coordinator
        image: ${druid_image}:${druid_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: coordinator
        resources:
          limits:
            cpu: "256m"
            memory: 2Gi
          requests:
            cpu: "256m"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        envFrom:
          - configMapRef:
              name: postgres-config              
        env:
          - name: POSTGRES_URL
            value: "postgres-cs.${namespace}.svc.cluster.local"
          - name: ZOOKEEPER_SERVER
            value: "zk-cs.${namespace}.svc.cluster.local"
          - name: DRUID_SERVICE_PORT
            value: "8081"
          - name: DRUID_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DRUID_SERVICE
            value: "coordinator"
          - name: DRUID_JVM_ARGS
            value: "-server -Xms1G -Xmx1G -XX:MaxDirectMemorySize=2G -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dderby.stream.error.file=var/druid/derby.log"
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_region
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_secret_key
          - name: BUCKET_STORAGE
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_storage
          - name: BUCKET_INDEX
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_index
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8081
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8081
        volumeMounts:
        - mountPath: /var/druid/
          name: data
      volumes:
      - name: druid-secret
        secret:
          secretName: druid-secret
      - name: data
        emptyDir: {}            