apiVersion: apps/v1
kind: Deployment
metadata:
  name: historical
  namespace: ${namespace}
  labels:
    app: historical
spec:
  replicas: ${historical_replicas}
  selector:
    matchLabels:
      app: historical
  template:
    metadata:
      labels:
        app: historical
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: historical
        image: ${druid_image}:${druid_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: historical
        resources:
          limits:
            cpu: "512m"
            memory: 8Gi
          requests:
            cpu: "256m"
            memory: 4Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        envFrom:
          - configMapRef:
              name: postgres-config              
        env:
          - name: POSTGRES_URL
            value: "postgres-cs.${namespace}.svc.cluster.local"
          - name: ZOOKEEPER_SERVER
            value: "zk-cs.${namespace}.svc.cluster.local"
          - name: DRUID_SERVICE_PORT
            value: "8083"
          - name: DRUID_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DRUID_SERVICE
            value: "historical"
          - name: DRUID_JVM_ARGS
            value: "-server -Xms4G -Xmx4G -XX:MaxDirectMemorySize=12G -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -XX:NewSize=4G -XX:MaxNewSize=4G -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_region
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_secret_key
          - name: BUCKET_STORAGE
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_storage
          - name: BUCKET_INDEX
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_index
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8083
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8083
        volumeMounts:
        - mountPath: /var/druid/
          name: data
      volumes:
      - name: druid-secret
        secret:
          secretName: druid-secret
      - name: data
        emptyDir: {}